### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by manasdk**
* Setup testing for hubot

### CODE REVIEW

**Comment by enykeev** [comment]
LGTM. The only thing that bothers me here is code style. Two space indentation and newline at the end of the file is preferred. Also, when in doubt, https://github.com/airbnb/javascript/tree/master/es5 is pretty decent guide to follow.

**Comment by manasdk** [comment]
Ah yeah style guide. Totally missed that part.

Wonder if sublime can deal with this part automatically or at least help liberally.

**Comment by enykeev** [comment]
Pretty sure it can. And if not, there is always Atom.

**Comment by manasdk** [comment]
Seems like I have a reasonable start here. Will merge this PR and focus on more tests. 

I have manually verified that hubt-stackstorm integration still works.

**Pull request merged**
