### PR TITLE
[RFR] Modify format regex to allow for defaults

### PR DESCRIPTION
**Pull request by manasdk**
* A format like google {{query}} {{count=10}} will not work for the following command literals
  1. google stackstorm
  2. google stackstorm 7
  3. google stackstorm count=5

### CODE REVIEW

**Comment by manasdk** [comment]
Fixes https://github.com/StackStorm/st2/issues/1537

**Comment by Kami** [comment]
LGTM

**Comment by manasdk** [comment]
Working on adding test so will merge after.

**Comment by manasdk** [comment]
Tests!

**Comment by Kami** [comment]
Nice, refactored code looks much better.

**Pull request merged**
