### PR TITLE
Slack post data should use new chat postMessage API

### LINKED ISSUE #121: Problem with @mention in Slack
When `result` message from the bot contains attachment, `@mention` doesn't work in Slack: 
### Good

> ^^ correct & highlighted @mention, you're notified in Slack
### Bad

> ^^ @mention is just a plain text here, no Slack notification from bot

---

As @emedvedev said, something was changed in Slack API.

Original discussion with code example: 
- https://github.com/armab/st2-chatops-aliases/pull/2

### PR DESCRIPTION
**Pull request by lakshmi-kannan**
Based on https://github.com/slackapi/hubot-slack/pull/355/files#diff-04c6e90faac2675aa89e2176d2eec7d8R86 and https://api.slack.com/methods/chat.postMessage#formatting

Also closes #121

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
Tested these changes in a hubot instance I spun up.

**Comment by jszaszvari** [comment]
This would break compatibility with all the "slack clones" out there as that API is very proprietary to just slack. 

There is probably 5-6 other solutions out there that are able to use hubot-stackstorm at the moment due to them being compatible with the old method.

**Comment by armab** [comment]
Bumping this version to  `0.5.1` -> `0.6.0` then, to reflect this change.
FYI it's needed because we switch to `hubot-slack` 4+ here https://github.com/StackStorm/st2chatops/pull/78

**Comment by jszaszvari** [comment]
Cool in the mean time everyone who doesn't use slack but uses a platform that's not compatible with slacks proprietary API will update and have all of their chat ops infrastructure stop working.

**Comment by armab** [comment]
@jszaszvari can you clarify in more details how?
I didn't work on this, but my understanding is that the change affects SlackDataPostHandler only which is responsible for Slack and so other adapters should just use their own handlers + custom hubot plugins.

**Comment by jszaszvari** [comment]
@armab Theres been a custom handler here for nearly 5 months that has not been looked at thats for one of the largest Slack competitors - I know of at least 6 different companies using this instead of slack and it just works out of the box without any modifications needed.

https://github.com/StackStorm/hubot-stackstorm/pull/135#issuecomment-315594543

I'm reading through the changes now, I might be mistaken on how it works - So Im trying to test, because when I apply this change, messages just stop coming through completely .

If the PR above could be looked at I know thats going to stop a lot of pain for a lot of people - I've been testing it in production now for a while and it works perfect. 

Just trying to figure  out why if i apply the changes that are coming out it all stops working.

**Comment by armab** [comment]
@jszaszvari Are you referring to any specific Hubot adapter?
Are you saying you're using `hubot-slack` adapter for Rocketchat? If so, I think the right way is to use Rocketchat with `hubot-rocketchat` hubot adapter.

Will it help if I'll merge + release https://github.com/StackStorm/hubot-stackstorm/pull/135 first?

**Comment by armab** [comment]
As figured during the testing, this also fixes https://github.com/StackStorm/hubot-stackstorm/issues/121

**Pull request merged**
