### PR TITLE
Add rocketchat

### PR DESCRIPTION
**Pull request by cheremushki**
Add support for RocketChat.

### CODE REVIEW

**Comment by cheremushki** [comment]
No thoughts/comments guys?

**Comment by LindsayHill** [comment]
@cheremushki we're not deliberately ignoring you! I know @bigmstone has GH reviews on his list of things to do. Should get done soon

**Comment by armab** [comment]
Related to https://github.com/StackStorm/st2/issues/3352

**Comment by jszaszvari** [comment]
How did I miss this awesomeness!

Great work. Going to try it out in my test environment.

**Comment by jszaszvari** [comment]
Been using this now for just over a week and working great!

screen shot 2017-07-27 at 2 00 25 am

Get some nice formatting back instead of a wall of plaintext

**Comment by jszaszvari** [comment]
This change could potentially break any sort of RC / Slack Clone functionality - https://github.com/StackStorm/hubot-stackstorm/pull/138

Although I'm still investigating how it could be avoided.

**Comment by jszaszvari** [comment]
This needs to be looked at considering they are about to break compatibility with all non slack platforms that don't have support for slacks new proprietary API

**Comment by cheremushki** [comment]
I'll take a look at refactoring as per the requested changes when I have some time.

**Comment by cheremushki** [comment]
Reordered the formatters to allow easier code review as requested.
Raised https://github.com/StackStorm/st2chatops/pull/88

**Comment by armab** [comment]
Thanks @cheremushki!
Will try it soon.

**Pull request merged**
